kubevirt/kubevirt-tekton-tasks

README.md
examples/pipelines/server-deployer/README.md
examples/pipelines/unit-tester/README.md
examples/pipelines/windows-installer/README.md
examples/pipelines/windows-installer/windows-installer-pipeline.yaml
examples/pipelines/windows-installer/windows-installer-pipelinerun.yaml
manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/openshift/kubevirt-tekton-tasks-openshift.yaml
tasks/cleanup-vm/README.md
tasks/cleanup-vm/manifests/cleanup-vm.yaml
tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
templates/execute-in-vm/manifests/execute-in-vm.yaml
templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml

Downloads a Windows Source ISO into a PVC and installs Windows into a new root PVC.
It uses Windows Sysprep to automatically install the system. 
The pipeline can be customized to support different installation requirements. 
The artifact of this pipeline is a PVC (backed by DataVolume) with a custom Windows installation. 
[README](https://github.com/suomiy/kubevirt-tekton-tasks/tree/win-pipeline/examples/pipelines/windows-installer)
Todo:

add windows-installer example pipeline

---

automation/e2e-deploy-resources.sh

kubevirt config map is deprecated and it is replaced by kubevirt CR.

replaced kubevirt config map by patching kubevirt CR

---

modules/copy-template/build/copy-template/Dockerfile
modules/create-vm/build/create-vm/Dockerfile
modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
modules/execute-in-vm/build/execute-in-vm/Dockerfile
modules/generate-ssh-keys/build/generate-ssh-keys/Dockerfile
modules/wait-for-vmi-status/build/wait-for-vmi-status/Dockerfile

Switch from golang builder image to ubi8
this pr changes golang builder image to ubi8 minimal, due to
dockerhub rate limits.
```
NONE
```

Switch from golang builder image to ubi8

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/create-vm/cmd/create-vm/main.go
modules/create-vm/pkg/constants/constants.go
modules/create-vm/pkg/utils/parse/clioptions.go
modules/create-vm/pkg/utils/parse/clioptions_test.go
modules/create-vm/pkg/vm/vm-provider.go
modules/create-vm/pkg/vmcreator/vm-creator.go
modules/tests/test/constants/create-vm.go
modules/tests/test/create_vm_from_manifest_test.go
modules/tests/test/create_vm_from_template_test.go
modules/tests/test/testconfigs/vm-test-config.go
tasks/create-vm-from-manifest/README.md
tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
tasks/create-vm-from-template/README.md
tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
templates/create-vm-from-manifest/manifests/create-vm-from-manifest-role.yaml
templates/create-vm-from-manifest/manifests/create-vm.yaml
templates/create-vm-from-template/manifests/create-vm-from-template-role.yaml

add startVM attribute for create-vm-from-template task
This attribute starts vm after creation
```
add startVM attribute for create-vm-from-template task
```

add startVM attribute for create-vm-from-template task

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/create-vm-from-manifest/README.md
tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
tasks/create-vm-from-template/README.md
tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
templates/create-vm-from-manifest/manifests/create-vm.yaml

add valid values for startVM attribute
```
NONE
```

add valid values for startVM attribute

---

modules/copy-template/build/copy-template/Dockerfile
modules/create-vm/build/create-vm/Dockerfile
modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
modules/execute-in-vm/build/execute-in-vm/Dockerfile
modules/generate-ssh-keys/build/generate-ssh-keys/Dockerfile
modules/modify-vm-template/build/modify-vm-template/Dockerfile
modules/wait-for-vmi-status/build/wait-for-vmi-status/Dockerfile

change golang version to new version 1.16
golang 1.15 is no longer available on ubi8 image
```
error: No package matches 'golang-1.15.*'
error: build error: error building at STEP "RUN microdnf install -y golang-1.15.* && microdnf clean all": error while running runtime: exit status 1
```
```
NONE
```

change golang version to new version 1.16

---

configs/create-vm-from-manifest.yaml
configs/create-vm-from-template.yaml
manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
tasks/create-vm-from-template/manifests/create-vm-from-template.yaml

bump version of create-vm-from-manifest and create-vm-from-template containers
```
NONE
```

bump version of create-vm-from-manifest and create-vm-from-template containers

---

modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-customize/pkg/constants/constants.go
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
modules/disk-virt-sysprep/pkg/constants/constants.go

switch to libguestfs-tools image for disk-virt-customize and disk-virt-sysprep
use quay.io/kubevirt/libguestfs-tools:v0.49.0 image as
base image for for disk-virt-customize and disk-virt-sysprep.
libguestfs-tools image contains all necessary libguestfs sw which is
used by kubevirt.
```
switch to kubevirt libguestfs-tools image for disk-virt-customize and disk-virt-sysprep
```

switch to libguestfs-tools image for disk-virt-customize and disk-virt-sysprep

---

modules/disk-virt-customize/build/disk-virt-customize/repos/CentOS-Stream-rhsrvany.repo
modules/disk-virt-customize/build/disk-virt-customize/repos/CentOS-Stream.repo
modules/disk-virt-sysprep/build/disk-virt-sysprep/repos/CentOS-Stream-rhsrvany.repo
modules/disk-virt-sysprep/build/disk-virt-sysprep/repos/CentOS-Stream.repo

update centos repos URL
Centos 8 is EOL, update URLs to centos stream 8
```
NONE
```

update centos repos URL

---

.github/workflows/release.yaml
.github/workflows/validate-no-offensive-lang.yml
makefile
scripts/build-release-images.sh
scripts/push-release-images.sh
scripts/release-var.sh
scripts/validate-no-offensive-lang.sh

add release automation and offense language validation via github actions
This PR adds release automation, which creates new images and deploy
manifests when new github release is done.
Add script which checks offense language and if any is found, fail test.
```
NONE
```

add release automation and offense language validation via github actions

---

.github/workflows/release.yaml

update golang version in github actions
github actions will now use golang 1.17
```
NONE
```

update golang version in github actions

---

.github/workflows/release.yaml

add step to GH actions to upload released manifests to TTO
this pr adds new step to GH actions, which creates a PR with
newly created manifests for okd and kubernetes
/hold I need to test if it works as expected
```
NONE
```

add step to GH actions to upload released manifests to TTO

---

manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/modify-vm-template/pkg/templates/template-provider.go
modules/modify-vm-template/pkg/utils/parse/clioptions.go
modules/modify-vm-template/pkg/utils/parse/clioptions_test.go
modules/sharedtest/testobjects/template/rhel-tiny.go
modules/tests/test/constants/modify-vm-template.go
modules/tests/test/modify-vm-template_test.go
modules/tests/test/testconfigs/modify-vm-template-test-config.go
modules/tests/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testobjects/template/rhel-tiny.go
tasks/modify-vm-template/README.md
tasks/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml

Add deleteDatavolumeTemplate parameter to modify-vm-template task
this parameter removes datavolume template from template and removes
all associated volumes and disks.
```
Add deleteDatavolumeTemplate parameter to modify-vm-template task
```

Add deleteDatavolumeTemplate parameter to modify-vm-template task

---

modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile

bump quay.io/kubevirt/libguestfs-tools image to v0.52.0
**Which issue(s) this PR fixes**:
Fixes https://github.com/kubevirt/kubevirt-tekton-tasks/issues/113
```
Bump quay.io/kubevirt/libguestfs-tools image to v0.52.0
```

bump quay.io/kubevirt/libguestfs-tools image to v0.52.0

---

manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/modify-vm-template/pkg/templates/template-provider.go
modules/modify-vm-template/pkg/utils/parse/clioptions.go
modules/modify-vm-template/pkg/utils/parse/clioptions_test.go
modules/tests/test/constants/modify-vm-template.go
modules/tests/test/modify-vm-template_test.go
modules/tests/test/testconfigs/modify-vm-template-test-config.go
tasks/modify-vm-template/README.md
tasks/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml

add datavolumeTemplates parameter to modify-vm-template task
This parameter can replace or add dataVolume template in vm definition.
If name is same, datavolume is replaced, if not, it is appended.
If deleteDatavolumeTemplate is set, first datavolumes are deleted
and then datavolumes from this attribute are added.
```
add datavolumeTemplates parameter to modify-vm-template task
```

add datavolumeTemplates parameter to modify-vm-template task

---

manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/tests/test/modify-vm-template_test.go
tasks/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml

The manifest was missing defaults for several parameters, which made it
necessary to declare empty values for them when invoking the task.
```release-note
Add missing defaults for modify-vm-template task parameters
```

Add missing defaults to modify-vm-template manifest

---

modules/tests/test/modify-vm-template_test.go

Copy paste typo...
```release-note
None
```

Fix typo in modify-vm-template test

---

manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/copy-template/pkg/templates/template-provider.go
modules/copy-template/pkg/utils/parse/clioptions.go
modules/copy-template/pkg/utils/parse/clioptions_test.go
modules/tests/test/constants/copy-template.go
modules/tests/test/copy_template_test.go
modules/tests/test/testconfigs/copy-template-config.go
tasks/copy-template/README.md
tasks/copy-template/manifests/copy-template.yaml
templates/copy-template/manifests/copy-template-role.yaml
templates/copy-template/manifests/copy-template.yaml

add Param allowReplace in copy template task
When this param is set, task will not fail, when template already
exists, but it will update already existing template with newly copied template
```
add param allowReplace in copy template task
```

add param allowReplace in copy template task

---

manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/modify-vm-template/pkg/templates/template-provider.go
modules/modify-vm-template/pkg/utils/parse/clioptions.go
modules/modify-vm-template/pkg/utils/parse/clioptions_test.go
modules/tests/test/constants/modify-vm-template.go
modules/tests/test/create_vm_common_test.go
modules/tests/test/modify-vm-template_test.go
modules/tests/test/testconfigs/modify-vm-template-test-config.go
tasks/modify-vm-template/README.md
tasks/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml

add new parameters to modify template task
this PR adds these params:
deleteVolumes: delete all VM volumes
deleteDisks: delete all VM disks
deleteTemplateParameters: delete all template parameters.
templateParameters: adds new template parameters
If delete params are set, volumes, disks, template params are added
after deletion
```
added new parameters to modify template task:
deleteVolumes: delete all VM volumes
deleteDisks: delete all VM disks
deleteTemplateParameters: delete all template parameters.
templateParameters: adds new template parameters
```

add new parameters to modify template task

---

automation/e2e-deploy-resources.sh

fix getting of kubevirt components latest release
previous command fetched latest releases according to date.
Current command fetch latest release according to version number.
```
NONE
```

fix getting of kubevirt components latest release

---

automation/generatetasks/build/Dockerfile

add gcc package into openshift ci builder image
```
NONE
```

add gcc package into openshift ci builder image

---

modules/tests/test/copy_template_test.go
modules/tests/test/create_datavolume_test.go
modules/tests/test/create_vm_from_manifest_test.go
modules/tests/test/create_vm_from_template_test.go
modules/tests/test/execute_and_cleanup_vm_test.go
modules/tests/test/generate_ssh_keys_test.go
modules/tests/test/modify-vm-template_test.go
modules/tests/test/wait_for_vmi_status_test.go

remove tests which doesn't have serviceAccount
Openshift tekton pipelines are setting default SA `pipeline` to taskRuns, which doesn't have SA, so these tests are failing
```
NONE
```

remove tests which doesn't have serviceAccount

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/create-vm/cmd/create-vm/main.go
modules/create-vm/pkg/utils/parse/clioptions.go
modules/create-vm/pkg/utils/parse/clioptions_test.go
modules/create-vm/pkg/vmcreator/vm-creator.go
modules/tests/test/constants/create-vm.go
modules/tests/test/create_vm_from_manifest_test.go
modules/tests/test/create_vm_from_template_test.go
modules/tests/test/testconfigs/vm-test-config.go
tasks/create-vm-from-manifest/README.md
tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
tasks/create-vm-from-template/README.md
tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
templates/create-vm-from-manifest/manifests/create-vm.yaml

add RunStrategy parameter to create vm tasks
if runStrategy param is set, vm.spec.running is set to nil, due to https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go#L315
```
add runStrategy parameter for create-vm tasks
```

add RunStrategy parameter to create vm tasks

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest.yaml
templates/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest-role.yaml

This is needed to allow cloning of DataVolumes.
See https://github.com/kubevirt/containerized-data-importer/blob/f9d4a4b4c8b17ddab992063be1531fad3b47f44a/pkg/clone/auth.go#L124
```release-note
None
```

Allow create-datavolume-from-manifest-role to create pods

---

modules/copy-template/pkg/templates/common-templates.go
modules/copy-template/pkg/templates/template-provider.go
modules/copy-template/pkg/templates/template-provider_test.go

remove all common-template labels / annotations in copy task
If these annotations / labels would stay in template, ssp operator would
reconcile newly copied template and that can lead to unpredicted
results.
```
Copy template task removes all common templates related labels / annotations
```

remove all common-template labels / annotations in copy task

---

manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/modify-vm-template/pkg/templates/template-provider.go
modules/modify-vm-template/pkg/utils/parse/clioptions.go
modules/modify-vm-template/pkg/utils/parse/clioptions_test.go
modules/tests/test/constants/modify-vm-template.go
modules/tests/test/modify-vm-template_test.go
modules/tests/test/testconfigs/modify-vm-template-test-config.go
tasks/modify-vm-template/README.md
tasks/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-vm-template/manifests/modify-vm-template-role.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml

With this parameter the modify-vm-template task can be instructed to
delete the specified template instead of modifying it.
```release-note
modify-vm-template: Add deleteTemplate parameter
```

modify-vm-template: Add deleteTemplate parameter

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/tests/test/create_datasource_test.go
modules/tests/test/create_datavolume_test.go
modules/tests/test/ds/conditions.go
modules/tests/test/ds/datasource.go
modules/tests/test/ds/operations.go
modules/tests/test/testconfigs/dv-ds-test-config.go
tasks/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest.yaml
templates/create-datavolume-from-manifest/create-datavolume-script.sh
templates/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest-role.yaml

enhance create-datavolume-task with ability to create datasources
the task will be able to create datasource and wait for it to finish.
The task was not renamed, because this is mostly mean as a fix for
release-v0.3 branch. New version of create-datavolume task will be
rewritten to go language and will have support for both datavolumes
and datasources
```release-note
create-datavolume task can create datasources objects
```

[release-v0.9.0] enable creating datasources in create-datavolume-task

---

modules/create-data-object/build/create-data-object/Dockerfile

Bump create-data-object golang version to 1.17 temporarily
It is needed so the task can be onboarded to the CI.
```release-note
None
```

Bump create-data-object golang version to 1.17 temporarily

---

examples/pipelines/windows10-installer/README.md
examples/pipelines/windows10-installer/getisourl.py

The getisourl.py script was added. It allows to obtain WIndows 10 ISO
download URLs in an automated way.
```release-note
Add script to obtain Windows 10 ISO download URL in an automated way
```

Add script to obtain Windows 10 ISO download URL in an automated way

---

automation/e2e-deploy-resources.sh

it takes some time until tekton is properly deployed
This commit adds a wait until clustertasks api kind is available
```
NONE
```

wait for tekton to be deployed

---

automation/e2e-deploy-resources.sh

wait for tekton pipelines webhook
e2e tests are failing, because tekton pipelines webhook is not online.
This change adds wait command which waits until webhook become available
```
NONE
```

wait for tekton pipelines webhook

---

examples/pipelines/server-deployer/server-deployer-pipelinerun.yaml
examples/pipelines/unit-tester/unit-tester-pipelinerun.yaml
examples/pipelines/virt-sysprep-updater/virt-sysprep-updater-pipelinerun.yaml
examples/pipelines/windows10-customize/windows10-customize-pipelinerun-kubernetes.yaml
examples/pipelines/windows10-customize/windows10-customize-pipelinerun-okd.yaml
examples/pipelines/windows10-installer/windows10-installer-pipelinerun-kubernetes.yaml
examples/pipelines/windows10-installer/windows10-installer-pipelinerun-okd.yaml

Change serviceAccountNames that is deprecated and causes error in pipelineRun examples .
**Which issue(s) this PR fixes**:
Fixes #178
```release-note
```
Signed-off-by: Ondrej Pokorny <opokorny@redhat.com>

Change serviceAccountNames that is deprecated in pipelineRun examples

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/create-data-object/cmd/create-data-object/main.go
modules/create-data-object/pkg/constants/constants.go
modules/create-data-object/pkg/dataobject/provider.go
modules/create-data-object/pkg/utils/parse/clioptions.go
modules/tests/test/constants/create-data-object.go
modules/tests/test/create_data_object_test.go
modules/tests/test/framework/framework.go
modules/tests/test/pipelines_test.go
modules/tests/test/tekton/pipelinerun.go
modules/tests/test/testconfigs/create-data-object-test-config.go
tasks/create-data-object/README.md
tasks/create-data-object/manifests/create-data-object.yaml
templates/create-data-object/manifests/create-data-object.yaml

add delete option to create-data-object task
When DeleteObject is set, Name and ObjectKind param has to be specified.
This functionality can delete single datavolume or datasource
```
add delete option to create-data-object task
```

add delete option to create-data-object task

---

modules/copy-template/build/copy-template/Dockerfile
modules/create-vm/build/create-vm/Dockerfile
modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
modules/execute-in-vm/build/execute-in-vm/Dockerfile
modules/generate-ssh-keys/build/generate-ssh-keys/Dockerfile
modules/modify-data-object/build/modify-data-object/Dockerfile
modules/modify-vm-template/build/modify-vm-template/Dockerfile
modules/wait-for-vmi-status/build/wait-for-vmi-status/Dockerfile

bump golang version to 1.18.4
```
bump golang version to 1.18.4
```

bump golang version to 1.18.4

---

modules/create-data-object/build/create-data-object/Dockerfile

remove create-data-object dockerfile
This dockerfile is no longer needed
```
NONE
```

remove create-data-object dockerfile

---

modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile

bump libguestfs image to version v0.55 in disk-virt tasks
```
bump libguestfs image to version v0.55
```

bump libguestfs image to version v0.55

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
templates/disk-virt-customize/manifests/disk-virt-customize.yaml
templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml

This adds more optional workspaces to disk-virt-customize and
disk-virt-sysprep so more ConfigMaps or Secrets can be used.
```release-note
disk-virt-[customize|sysprep] now have 10 optional workspaces to mount ConfigMaps or Secrets
```

disk-virt-[customize|sysprep]: Add more optional workspaces

---

modules/modify-data-object/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testobjects/datavolume/datavolumes.go
modules/sharedtest/testobjects/datavolume/datavolumes.go
modules/tests/test/create_vm_common_test.go
modules/tests/test/create_vm_from_manifest_test.go
modules/tests/test/execute_and_cleanup_vm_test.go
modules/tests/test/framework/testoptions/test-options.go
modules/tests/test/generate_ssh_keys_test.go
modules/tests/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testobjects/datavolume/datavolumes.go

add skip option for tests which doesn't have to run in downstream
add cdi annotation to bind immediatelly for datavolume tests, otherwise datavolumes stays in waitForFirstConsumer state and test fails.
These changes are needed to be able to run tests in downstream
```
NONE
```

add skip option for tests which doesn't have to run in downstream

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-customize/pkg/execute/executor.go
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
modules/disk-virt-sysprep/pkg/execute/executor.go
tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
templates/disk-virt-customize/manifests/disk-virt-customize.yaml
templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml

in ocp 4.12 running under root causes an issue with permissions.
This PR removes the securityContext.runAsUser from disk-virt tasks
manifests, and updates the code to untar libguestfs appliance files to
${HOME}. After untar, script sets correct LIBGUESTFS_PATH env variable.
With this approach, the script does not have to run under root.
```
NONE
```

remove securityContext.runAsUser from disk-virt tasks

---

modules/modify-data-object/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testobjects/datavolume/datavolumes.go
modules/sharedtest/testobjects/datavolume/datavolumes.go
modules/tests/test/pipelines_test.go
modules/tests/vendor/github.com/kubevirt/kubevirt-tekton-tasks/modules/sharedtest/testobjects/datavolume/datavolumes.go

disable garbage collector in datavolume tests by adding special annotation
```
NONE
```

disable garbage collector in datavolume tests by adding special annotation

---

.github/workflows/release.yaml

update golang version to 1.18 in github actions
```
NONE
```

update golang version to 1.18 in github actions

---

automation/e2e-deploy-resources.sh

hardcode older cdi version to prevent automatic DV garbage collecting
CDI 1.55.0 introduced automatic GC of finished DV. Tests in v0.9 are not prepared for it and I don't want to introduce any new code which updates behaviour of tests.
```
NONE
```

[release-v0.9] hardcode older cdi version to prevent automatic DV garbage collecting

---

modules/tests/test/create_vm_from_template_test.go

add deploy namespace to e2e test
in d/s one test is failing, due to missing namespace during creation of VM. This commit adds it.
```
NONE
```

add deploy namespace to e2e test

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
templates/disk-virt-customize/manifests/disk-virt-customize.yaml
templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml

Remove runAs from disk-virt tasks
these tasks don't have to run as root with latest changes. this commit removes the requirement to run as root
Fixes #
```
Remove runAsUser from disk-virt tasks
```

[release-v0.9] Remove runAs from disk-virt tasks

---

modules/create-vm/pkg/templates/template-provider.go

fix:remove namespace when processing template
In d/s e2e when trying to process template, api replied with panic
(panic: the namespace of the provided object does not match the
namespace sent on the request), because namespace send in request
is different than namespace in original template. This can be solved
by removing namespace from processed template and specifying only
namespace in request
```
NONE
```

fix:remove namespace when processing template

---

modules/disk-virt-customize/build/disk-virt-customize/Dockerfile
modules/disk-virt-customize/pkg/constants/constants.go
modules/disk-virt-customize/pkg/execute/executor.go
modules/disk-virt-sysprep/build/disk-virt-sysprep/Dockerfile
modules/disk-virt-sysprep/pkg/constants/constants.go
modules/disk-virt-sysprep/pkg/execute/executor.go

**What this PR does / why we need it**: 
chore: new libguestfs appliance does not need extraction
new libguestfs container contains appliance, which does not need extraction. This PR updates the code of disk-virt-* tasks to use appliance files directly without untaring
```
disk-virt-* tasks are using appliance files directly without untaring
```

chore: new libguestfs appliance does not need extraction

---

configs/modify-windows-iso-file.yaml
manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/modify-data-object/build/modify-data-object/Dockerfile
modules/modify-data-object/pkg/constants/constants.go
tasks/modify-windows-iso-file/README.md
tasks/modify-windows-iso-file/examples/taskruns/modify-windows-iso-file-taskrun.yaml
tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
templates/modify-windows-iso-file/examples/modify-windows-iso-file-taskrun.yaml
templates/modify-windows-iso-file/generate-task.yaml
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
templates/modify-windows-iso-file/readmes/README.md

feat: add modify-windows-iso-file task
this tasks modifies windows iso and replaces prompt bootloader with no-prompt bootloader. This helps during automation of win 11 installation.
We can't do any modifications inside iso, because by default win iso is in UDF format and read only. To extract iso the guestfish is used. After extraction, bootloader is replaced with no-prompt one. The extracted files are then packed back by xorriso. The result iso is then converted to raw format and stored back to original pvc as a replacement of original iso.
```
add modify-windows-iso-file task
```

feat: add modify-windows-iso-file task

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/modify-data-object/pkg/dataobject/provider.go
modules/tests/test/modify_data_object_test.go
tasks/modify-data-object/manifests/modify-data-object.yaml
templates/modify-data-object/manifests/modify-data-object-role.yaml

fix: delete pvc when datavolume is not found
Datavolumes are garbage collected, when they are successfully imported. This means that when allowReplace param is set and datavolume is GC and pvc exists, modify-data-object did not delete pvc. This PR changes the behaviour so MDO task tries to delete the existing pvc, when datavolume does not exists.
```
fix: delete pvc when datavolume is not found
```

fix: delete pvc when datavolume is not found

---

README.md
examples/pipelines/windows-customize/README.md
examples/pipelines/windows-customize/windows10-customize-pipelinerun-kubernetes.yaml
examples/pipelines/windows-customize/windows10-customize-pipelinerun-okd.yaml
examples/pipelines/windows-customize/windows11-customize-pipelinerun-okd.yaml
examples/pipelines/windows-customize/windows2k22-customize-pipelinerun-okd.yaml
examples/pipelines/windows-efi-installer/README.md
examples/pipelines/windows-efi-installer/getisourl.py
examples/pipelines/windows-efi-installer/windows11-installer-pipelinerun-okd.yaml
examples/pipelines/windows-efi-installer/windows2k22-installer-pipelinerun-okd.yaml
tasks/modify-windows-iso-file/README.md
templates/modify-windows-iso-file/readmes/README.md

feat: add documentation for windows-customize and windows-efi-installer example pipelines
This commits adds/updates documentation for windows-customize and windows-efi-installer example pipelines. These pipelines can be used to install and customize win10, 11, 2k22 from iso with tekton.
```
Add documentation for windows-customize and windows-efi-installer example pipelines
```

feat: add documentation for windows-customize and windows-efi-installer example pipelines

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
modules/modify-data-object/pkg/constants/constants.go
modules/modify-data-object/pkg/dataobject/provider.go
modules/modify-data-object/pkg/utils/parse/clioptions.go
tasks/modify-data-object/README.md
tasks/modify-data-object/manifests/modify-data-object.yaml
templates/modify-data-object/manifests/modify-data-object.yaml

feat: add delete PVC option for modify-data-object task
This PR adds ability to delete PVC via modify-data-object task. This will help during efi pipeline, because when the imported PVC is mounted to modify-windows-iso pod, it can't be deleted, because the PVC contains finalizer to prevent dataloss when mounted to pod. We have to include the delete pvc step into efi pipeline, so the pvc can be moved to terminating state and deleted when modify-windows-iso pod is deleted
```
feat: modify-data-object task can delete PVC
```

feat: add delete PVC option for modify-data-object task

---

scripts/cluster-test.sh

fix: junit report file path
this PR fixes junit file report location. Without this change, make e2e tests ends with error
```
NONE
```

fix: junit report location

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml

fix: increase emptyDir size in modify-windows-iso-file task to 12Gi
When using larger windows iso, 7Gi might not be enought. This commit increases the emptyFolder size to 12Gi which should be enough for most of the use cases.
**Which issue(s) this PR fixes**:
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2177279
```
increase emptyDir size in modify-windows-iso-file task to 12Gi
```

fix: increase emptyDir size in modify-windows-iso-file task to 12Gi

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml

feat:Add check if required no-prompt bootloader files exists
This commit adds a check to modify-windows-iso tasks if required no-prompt bootloader files exists. If not, exit before doing any actions with those files. This will help user to debug whats wrong, when task unexpectedly exits.
```
modify-windows-iso tasks exists if no-prompt bootloader files are not found
```

feat:Add check if required no-prompt bootloader files exists

---

.github/workflows/release.yaml

feat: update github release script
This commit changes behaviour of github release script to do a new PR with tekton tasks manifests to SSP operator instead of TTO.
```
NONE
```

feat: update github release script

---

modules/tests/test/constants/timeout.go
modules/tests/test/tekton/taskrun.go

chore: increase timeout for taskRun tests
add debug line, which will print taskRun in stdout in case of timeout
```
NONE
```

chore: increase timeout for taskRun tests

---

automation/e2e-deploy-resources.sh
modules/tests/test/disk_virt_libguestfs_tasks_test.go
modules/tests/test/execute_and_cleanup_vm_test.go
modules/tests/test/runner/taskrunrunner.go
modules/tests/test/tekton/taskrun.go
modules/tests/test/wait_for_vmi_status_test.go

chore: debug wait-for-vmi and execute-in-vm tests
This PR updates behaviour of WaitForTaskRunState function, which will
not fail after timeout, but instead it saves error to struct which can be then
recognized and run some after code (in this case print out status of VM)
```
NONE
```

[release-v0.13] chore: debug wait-for-vmi and execute-in-vm tests

---

modules/tests/test/dataobject/operations.go

The test `TaskRun fails and DataVolume is modified but does not import successfully` checks if a DV has failed by asserting several fields on the DV. One of them is `conditions[cdiv1beta1.DataVolumeBound].Status == v1.ConditionTrue`. In the current version of CDI, if a DV fails to fetch the import link, which is the scenario in this test, the underlining PVC is not bound. Therefore, the test assertion fails even if the DV has failed to import.
It changes the logic of the function `HasDataVolumeFailedToImport` to check if a DV import has failed. Drops assert `conditions[cdiv1beta1.DataVolumeBound].Status == v1.ConditionTrue`.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …

fix: change the condition to consider a DV import failed

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
templates/create-vm-from-manifest/manifests/create-vm-from-manifest-role.yaml
templates/create-vm-from-template/manifests/create-vm-from-template-role.yaml
templates/generate-ssh-keys/manifests/generate-ssh-keys-role.yaml

It replaces all `*` verbs by individual verbs required to run all intended operations. 
It drops the usage of `*` verbs, replacing them by individual verbs strictly required by the test suite, i.e. unit tests and functional tests. The auditing process has been split in the next action items:
* Deploying the operator in a CRC cluster and running the unit and function test.
* Deploying the operator in a 3 masters and 3 workers nodes and running the unit and functional tests.
jira-ticket: [CNV-24031](https://issues.redhat.com/browse/CNV-24031)
Fixes # …

rbac: Audit `*` verbs

---

templates/cleanup-vm/generate-task.yaml
templates/copy-template/generate-task.yaml
templates/create-vm-from-manifest/generate-task.yaml
templates/create-vm-from-template/generate-task.yaml
templates/disk-virt-customize/generate-task.yaml
templates/disk-virt-sysprep/generate-task.yaml
templates/execute-in-vm/generate-task.yaml
templates/generate-ssh-keys/generate-task.yaml
templates/modify-data-object/generate-task.yaml
templates/modify-vm-template/generate-task.yaml
templates/modify-windows-iso-file/generate-task.yaml
templates/wait-for-vmi-status/generate-task.yaml

fix: replace include with include_tasks
ansible.builtin.include has been deprecated and removed from ansible-core. Because of that, release scripts are not working - https://github.com/kubevirt/kubevirt-tekton-tasks/actions/runs/7183095492/job/19561070924
```
NONE
```

fix: replace include with include_tasks

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/cleanup-vm/manifests/cleanup-vm.yaml
tasks/copy-template/manifests/copy-template.yaml
tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
tasks/execute-in-vm/manifests/execute-in-vm.yaml
tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
tasks/modify-data-object/manifests/modify-data-object.yaml
tasks/modify-vm-template/manifests/modify-vm-template.yaml
tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
templates/copy-template/manifests/copy-template.yaml
templates/create-vm-from-manifest/manifests/create-vm.yaml
templates/disk-virt-customize/manifests/disk-virt-customize.yaml
templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
templates/execute-in-vm/manifests/execute-in-vm.yaml
templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
templates/modify-data-object/manifests/modify-data-object.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml

feat: bump api version of task to v1 in manifests
manifests were using v1beta api version. This commit changes it to v1.
```
feat: bump api version of task to v1 in manifests
```

feat: bump api version of task to v1 in manifests

---

.github/workflows/test-yaml-consistency.yaml
scripts/test-yaml-consistency.sh

feat: simplify test-yaml-consistency script
This commit simplifies the scripts/test-yaml-consistency.sh script and moves it to GH actions CI from ocp ci. OCP CI is doing changes to cloned repo and that causes false positive records in git status --porcelain. On GH actions this is working.
```
NONE
```

feat: simplify test-yaml-consistency script

---

manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
manifests/okd/kubevirt-tekton-tasks-okd.yaml
tasks/cleanup-vm/cleanup-vm.yaml
tasks/copy-template/copy-template.yaml
tasks/create-vm-from-manifest/create-vm-from-manifest.yaml
tasks/create-vm-from-template/create-vm-from-template.yaml
tasks/disk-virt-customize/disk-virt-customize.yaml
tasks/disk-virt-sysprep/disk-virt-sysprep.yaml
tasks/execute-in-vm/execute-in-vm.yaml
tasks/generate-ssh-keys/generate-ssh-keys.yaml
tasks/modify-data-object/modify-data-object.yaml
tasks/modify-vm-template/modify-vm-template.yaml
tasks/modify-windows-iso-file/modify-windows-iso-file.yaml
tasks/wait-for-vmi-status/wait-for-vmi-status.yaml
templates/copy-template/manifests/copy-template.yaml
templates/create-vm-from-manifest/manifests/create-vm.yaml
templates/disk-virt-customize/manifests/disk-virt-customize.yaml
templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
templates/execute-in-vm/manifests/execute-in-vm.yaml
templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
templates/modify-data-object/manifests/modify-data-object.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml

feat: add artifact hub annotations
this commit adds special artifact hub annotations, which add information about maintainers, recommendations, provider, ... These annotation are used only by artifact hub.
Signed-off-by: Karel Simon <ksimon@redhat.com>
```
Add artifact hub annotations
```

feat: add artifact hub annotations

---

build/Containerfile.DiskVirt

feat: update libguestfs container to v1.1.1
this commit updates libguestfs container to newest available v1.1.1.
I created manually this PR, because https://github.com/kubevirt/project-infra/pull/3186 is not working and I need to investigate why its not working
```
Update libguestfs container to v1.1.1
```

feat: update libguestfs container to v1.1.1

---

.github/workflows/release.yaml

feat: disable PRs to ssp operator during release
tekton tasks will no longer be part of ssp operator
```
NONE
```

feat: disable PRs to ssp operator during release

---

tasks/cleanup-vm/examples/taskruns/cleanup-vm-simple-taskrun.yaml
tasks/cleanup-vm/examples/taskruns/cleanup-vm-with-ssh-taskrun.yaml
tasks/copy-template/examples/taskruns/copy-template-taskrun.yaml
tasks/create-vm-from-manifest/examples/taskruns/create-vm-from-manifest-taskrun.yaml
tasks/create-vm-from-template/examples/taskruns/create-vm-from-template-taskrun.yaml
tasks/disk-virt-customize/examples/taskruns/disk-virt-customize-taskrun-workspace.yaml
tasks/disk-virt-customize/examples/taskruns/disk-virt-customize-taskrun.yaml
tasks/disk-virt-sysprep/examples/taskruns/disk-virt-sysprep-taskrun-workspace.yaml
tasks/disk-virt-sysprep/examples/taskruns/disk-virt-sysprep-taskrun.yaml
tasks/execute-in-vm/examples/taskruns/execute-in-vm-with-ssh-taskrun.yaml
tasks/generate-ssh-keys/examples/taskruns/generate-ssh-keys-advanced-taskrun.yaml
tasks/generate-ssh-keys/examples/taskruns/generate-ssh-keys-simple-taskrun.yaml
tasks/modify-data-object/examples/taskruns/modify-data-object-taskrun.yaml
tasks/modify-vm-template/examples/taskruns/modify-vm-template-taskrun.yaml
tasks/modify-windows-iso-file/examples/taskruns/modify-windows-iso-file-taskrun.yaml
tasks/wait-for-vmi-status/examples/taskruns/wait-for-vmi-status-taskrun.yaml
templates/cleanup-vm/examples/cleanup-vm-taskrun.yaml
templates/copy-template/examples/copy-template-taskrun.yaml
templates/create-vm-from-manifest/examples/create-vm-from-manifest-taskrun.yaml
templates/create-vm-from-template/examples/create-vm-from-template-taskrun.yaml
templates/disk-virt-customize/examples/disk-virt-customize-taskrun-workspace.yaml
templates/disk-virt-customize/examples/disk-virt-customize-taskrun.yaml
templates/disk-virt-sysprep/examples/disk-virt-sysprep-taskrun-workspace.yaml
templates/disk-virt-sysprep/examples/disk-virt-sysprep-taskrun.yaml
templates/execute-in-vm/examples/execute-in-vm-taskrun.yaml
templates/generate-ssh-keys/examples/generate-ssh-keys-taskrun.yaml
templates/modify-data-object/examples/modify-data-object-taskrun.yaml
templates/modify-vm-template/examples/modify-vm-template-taskrun.yaml
templates/modify-windows-iso-file/examples/modify-windows-iso-file-taskrun.yaml
templates/wait-for-vmi-status/examples/wait-for-vmi-status-taskrun.yaml

fix: tekton version in templates and tasks
fix tekton version to v1 in templates and tasks
```
Use tekton v1 in taskruns
```

fix: tekton version in templates and tasks

---

examples/pipelines/server-deployer/server-deployer-pipeline.yaml
examples/pipelines/virt-sysprep-updater/virt-sysprep-updater-pipeline.yaml

This version is now deprecated in favour of v1.
Fixes #https://github.com/kubevirt/ssp-operator/issues/716
```release-note
NONE
```

fix: Remove use of kubevirt.io/v1alpha3 in example pipelines

---

scripts/ansible/branding.yaml
templates/cleanup-vm/generate-task.yaml
templates/copy-template/generate-task.yaml
templates/copy-template/manifests/copy-template.yaml
templates/create-vm-from-manifest/generate-task.yaml
templates/create-vm-from-manifest/manifests/create-vm.yaml
templates/create-vm-from-template/generate-task.yaml
templates/disk-virt-customize/generate-task.yaml
templates/disk-virt-customize/manifests/disk-virt-customize.yaml
templates/disk-virt-sysprep/generate-task.yaml
templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
templates/execute-in-vm/generate-task.yaml
templates/execute-in-vm/manifests/execute-in-vm.yaml
templates/generate-ssh-keys/generate-task.yaml
templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
templates/modify-data-object/generate-task.yaml
templates/modify-data-object/manifests/modify-data-object.yaml
templates/modify-vm-template/generate-task.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-windows-iso-file/generate-task.yaml
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
templates/wait-for-vmi-status/generate-task.yaml
templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml

chore: replace hardcoded annotations in templates with variables
To enable automation of OCP V releases of tekton tasks, this commit updates template manifests to use variables in annotations.
```
NONE
```

chore: replace hardcoded annotations in templates with variables

---

automation/generatetasks/build/Dockerfile

chore: update fedora version in CI image
Update fedora version to 39 in test base image.
```
NONE
```

chore: update fedora version in CI image

---

build/Containerfile.DiskVirt
release/pipelines/windows-bios-installer/windows-bios-installer.yaml
release/pipelines/windows-efi-installer/windows-efi-installer.yaml
templates-pipelines/windows-bios-installer/manifests/windows-bios-installer.yaml
templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml

chore: update libguestfs and virtio versions
this commit updates virtio and libguestfs versions to latest possible
```
Update libguestfs and virtio versions to 1.2.0
```

chore: update libguestfs and virtio versions

---

release/pipelines/windows-bios-installer/README.md
release/pipelines/windows-customize/README.md
release/pipelines/windows-efi-installer/README.md
templates-pipelines/windows-bios-installer/README.md
templates-pipelines/windows-customize/README.md
templates-pipelines/windows-efi-installer/README.md

chore: improve README of pipelines
this commit adds few notes about behaviour of pipelines and requirement to have ConfigMaps created before running pipelineRun.
```
NONE
```

chore: improve README of pipelines

---

release/pipelines/windows-bios-installer/README.md
release/pipelines/windows-bios-installer/pipelineruns/pipelineruns.yaml
release/pipelines/windows-customize/README.md
release/pipelines/windows-customize/pipelineruns/pipelineruns.yaml
release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
templates-pipelines/windows-bios-installer/pipelineruns/pipelineruns.yaml
templates-pipelines/windows-customize/pipelineruns/pipelineruns.yaml
templates-pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml

fix: fix PipelineRun examples
this commit fixes wrong kind in pipelinerun and adds security context in efi pipelineruns. This is necessary when PipelineRun uses resolver. Then the modify-windows-iso-file task runs under different user and group.
```
NONE
```

fix: fix PipelineRun examples

---

release/pipelines/windows-bios-installer/README.md
release/pipelines/windows-efi-installer/README.md
templates-pipelines/windows-bios-installer/README.md
templates-pipelines/windows-efi-installer/README.md

fix: url of getisourl.py script in pipeline readmes
```
fix: url of getisourl.py script in pipeline readmes
```

fix: url of getisourl.py script in pipeline readmes

---

README.md
release/pipelines/windows-efi-installer/README.md
release/tasks/modify-windows-iso-file/modify-windows-iso-file.yaml
templates-pipelines/windows-efi-installer/README.md
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml

fix: fix wrong pipeline paths in READMEs
```
fix: fix wrong pipeline paths in READMEs
```

fix: fix wrong pipeline paths in READMEs

---

scripts/ansible/common.yaml
templates-pipelines/windows-bios-installer/manifests/windows-bios-installer.yaml
templates-pipelines/windows-bios-installer/pipelineruns/pipelineruns.yaml
templates-pipelines/windows-customize/manifests/windows-customize.yaml
templates-pipelines/windows-customize/pipelineruns/pipelineruns.yaml
templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml
templates-pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
templates/cleanup-vm/examples/cleanup-vm-taskrun.yaml
templates/copy-template/examples/copy-template-taskrun.yaml
templates/copy-template/manifests/copy-template.yaml
templates/create-vm-from-manifest/examples/create-vm-from-manifest-taskrun.yaml
templates/create-vm-from-manifest/manifests/create-vm.yaml
templates/create-vm-from-template/examples/create-vm-from-template-taskrun.yaml
templates/disk-virt-customize/examples/disk-virt-customize-taskrun.yaml
templates/disk-virt-customize/manifests/disk-virt-customize.yaml
templates/disk-virt-sysprep/examples/disk-virt-sysprep-taskrun.yaml
templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
templates/execute-in-vm/examples/execute-in-vm-taskrun.yaml
templates/execute-in-vm/manifests/execute-in-vm.yaml
templates/generate-ssh-keys/examples/generate-ssh-keys-taskrun.yaml
templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
templates/modify-data-object/examples/modify-data-object-taskrun.yaml
templates/modify-data-object/manifests/modify-data-object.yaml
templates/modify-vm-template/examples/modify-vm-template-taskrun.yaml
templates/modify-vm-template/manifests/modify-vm-template.yaml
templates/modify-windows-iso-file/examples/modify-windows-iso-file-taskrun.yaml
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
templates/wait-for-vmi-status/examples/wait-for-vmi-status-taskrun.yaml
templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml

chore: enable setting catalog version without "v" prefix
this commit allows to set REMOVE_CATALOG_VERSION_PREFIX env variable, which will remove "v" prefix from version in catalog version - e.g. 0.19.0 when true vs v0.19.0 when false.
This will help in DS where OCP catalog removes v from version. This commit also replaces all version variables from catalog version and replaces it with catalog_version which can hold version with or without v prefix
Signed-off-by: Karel Simon <ksimon@redhat.com>
```
NONE
```

chore: enable setting catalog version without "v" prefix

---

release/pipelines/windows-bios-installer/README.md
release/pipelines/windows-customize/README.md
release/pipelines/windows-efi-installer/README.md
templates-pipelines/windows-bios-installer/README.md
templates-pipelines/windows-customize/README.md
templates-pipelines/windows-efi-installer/README.md

chore: add link to example configmaps for pipelines to README of each pipeline
this commit adds a link to example configmaps for each pipeline in each pipeline's README.
```
NONE
```
@akrejcir, @jcanocan, @0xFelix

chore: add link to example configmaps for pipelines to README of each

---

automation/e2e-pipelines/test-files/windows10-customize-pipelinerun.yaml
automation/e2e-pipelines/test-files/windows10-installer-pipelinerun.yaml
automation/e2e-pipelines/test-files/windows11-customize-pipelinerun.yaml
automation/e2e-pipelines/test-files/windows2k22-customize-pipelinerun.yaml
automation/e2e-pipelines/test-files/windows2k22-installer-pipelinerun.yaml
release/pipelines/windows-bios-installer/README.md
release/pipelines/windows-bios-installer/windows-bios-installer.yaml
release/pipelines/windows-customize/README.md
release/pipelines/windows-customize/windows-customize.yaml
release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/windows-efi-installer.yaml
templates-pipelines/windows-bios-installer/README.md
templates-pipelines/windows-bios-installer/manifests/windows-bios-installer.yaml
templates-pipelines/windows-customize/README.md
templates-pipelines/windows-customize/manifests/windows-customize.yaml
templates-pipelines/windows-efi-installer/README.md
templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml

chore: remove namespace params from pipelines
Since the regular users doesn't normally have access to different namespaces, multi namespace use case doesn't make sense. And since we want to have the pipelines as simple as possible, the multi namespace use case adds a lot of complexity with creating RBAC objects and correctly binding them to pipelines.
```
chore: remove namespace params from pipelines
```

chore: remove namespace params from pipelines

---

release/pipelines/windows-efi-installer/README.md
templates-pipelines/windows-efi-installer/README.md

fix: readme of windows efi installer pipeline
One step was removed from pipeline and README has to be adjusted
```
fix: readme of windows efi installer pipeline
```

fix: readme of windows efi installer pipeline

---

modules/modify-data-object/pkg/dataobject/provider.go

chore: improve logs in modify-data-object
this commit adds functionality, which will print out, when task is waiting for import to be finished, or when waiting until object is deleted.
```
NONE
```

chore: improve logs in modify-data-object

---

release/pipelines/windows-bios-installer/README.md
release/pipelines/windows-bios-installer/configmaps/windows-bios-installer-configmaps.yaml
release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/configmaps/windows-efi-installer-configmaps.yaml
scripts/deploy-pipelines.sh
templates-pipelines/windows-bios-installer/README.md
templates-pipelines/windows-bios-installer/configmaps/windows-bios-installer-configmaps.yaml
templates-pipelines/windows-efi-installer/README.md
templates-pipelines/windows-efi-installer/configmaps/windows-efi-installer-configmaps.yaml

disable AcceptEula tag in autounattend.xml ConfigMaps
Before running pipelines, users should uncomment the AcceptEula tag in ConfigMaps containing autounattend.xml
```
Disable AcceptEula tag in autounattend.xml ConfigMaps
```

chore: disable AcceptEula tag in autounattend.xml ConfigMaps

---

modules/sharedtest/testobjects/alpine-vm.go
modules/sharedtest/testobjects/fedora-cloud-vm.go
modules/sharedtest/testobjects/template/cirros-tiny.go
test/disk_virt_libguestfs_tasks_test.go

chore: download bootsources from quay instead of dockerhub in e2e tests
increase memory requirements for VMs
```
chore: download bootsources from quay instead of dockerhub in e2e tests
```

chore: download bootsources from quay instead of dockerhub

---

test/pipelines_test.go
test/testconfigs/disk-virt-libguestfs-tasks-test-config.go

fix: set RunAsUser and fsGroup for disk-virt tests
Some clusters can set wrong UID, GID for mounted PVCs. That might cause issues, that PVC is inaccessible for disk-virt binary. This commit updates disk-virt tests to set up RunAsUser and FSGroup attributes with id 107, the same as is used for disks inside PVC. That will make sure the disks are accessible by disk-virt binaries
```
NONE
```

fix: set RunAsUser and fsGroup for disk-virt tests

---

release/pipelines/windows-efi-installer/README.md
release/tasks/modify-windows-iso-file/modify-windows-iso-file.yaml
templates-pipelines/windows-efi-installer/README.md
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml

chore: improve error message in modify-windows-iso and README.md
the task expect ISO in some format. Improve the error message to indicate user, that task will not work without correct ISO file. Add command to generate sha256 checksum of the file.
```
NONE
```

chore: improve error message in modify-windows-iso and README.md

---

.gitignore

fix: folders in gitignore
Fix rules to ignore folder manifests and .idea only in the root of the project
```
NONE
```

fix: folders in gitignore

---

scripts/makefile-snippets/makefile-release.mk

fix: release version in scripts/makefile-snippets/makefile-release.mk
```
NONE
```

fix: release version in scripts/makefile-snippets/makefile-release.mk

---

modules/modify-data-object/pkg/dataobject/provider.go

fix: allowReplace param for datasource in modify-data-object task
when datasource does not exists and allowReplace param is set to true, the task fails, because it could not find the object. This commit adds check if the error returned is notFound and if yes, do not return the error
```
fix: allowReplace param for datasource in modify-data-object task
```

fix: allowReplace param for datasource in modify-data-object task

---

scripts/deploy-pipelines.sh

fix: remove bios pipeline leftover from deploy-pipelines.sh script
```
NONE
```

fix: remove bios pipeline leftover from deploy-pipelines.sh script

---

automation/e2e-pipelines/test-files/windows10-customize-pipelinerun.yaml
automation/e2e-pipelines/test-files/windows10-installer-pipelinerun.yaml
automation/e2e-pipelines/test-files/windows2k22-customize-pipelinerun.yaml
automation/e2e-pipelines/test-files/windows2k22-installer-pipelinerun.yaml
release/pipelines/windows-customize/README.md
release/pipelines/windows-customize/pipelineruns/pipelineruns.yaml
release/pipelines/windows-customize/windows-customize.yaml
release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
release/pipelines/windows-efi-installer/windows-efi-installer.yaml
templates-pipelines/windows-customize/manifests/windows-customize.yaml
templates-pipelines/windows-customize/pipelineruns/pipelineruns.yaml
templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml
templates-pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml

chore: change all preferences to use virtio in pipelines
Pipelines are installing virtio drivers and VMs should use the preferences with virtio bus
This PR is follow up of https://github.com/kubevirt/kubevirt-tekton-tasks/pull/409
```
chore: change all preferences to use virtio in pipelines
```

chore: change all preferences to use virtio in pipelines

---

release/pipelines/windows-customize/README.md
release/pipelines/windows-efi-installer/README.md
templates-pipelines/windows-customize/README.md
templates-pipelines/windows-efi-installer/README.md

chore: add mention about default SA in pipeline readme
by default tekton does not create default SA pipeline in namespaces which start with name openshift or kube. In case user tries to run the pipeline in that namespace, the pipeline will fail. To fix this user has to create the SA manually, or reference different SA in PipelineRun.
```
NONE
```

chore: add mention about default SA in pipeline readme

---

release/pipelines/windows-customize/README.md
release/pipelines/windows-customize/windows-customize.yaml
release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/windows-efi-installer.yaml
templates-pipelines/windows-customize/README.md
templates-pipelines/windows-customize/manifests/windows-customize.yaml
templates-pipelines/windows-efi-installer/README.md
templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml

chore: pipelines create DataSource
Pipelines now creates DataSource object, which is used by UI and is pointing to result DV/PVC. The DataSource will not be deleted when the PipelineRun is finished.
```
chore: pipelines create DataSource
```

chore: pipelines create DataSource

---

release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
release/tasks/disk-virt-customize/README.md
release/tasks/disk-virt-customize/examples/taskruns/disk-virt-customize-taskrun-resolver.yaml
release/tasks/disk-virt-customize/examples/taskruns/disk-virt-customize-taskrun-workspace.yaml
release/tasks/disk-virt-sysprep/README.md
release/tasks/disk-virt-sysprep/examples/taskruns/disk-virt-sysprep-taskrun-resolver.yaml
release/tasks/disk-virt-sysprep/examples/taskruns/disk-virt-sysprep-taskrun-workspace.yaml
templates-pipelines/windows-efi-installer/README.md
templates-pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
templates/disk-virt-customize/examples/disk-virt-customize-taskrun-workspace.yaml
templates/disk-virt-customize/examples/disk-virt-customize-taskrun.yaml
templates/disk-virt-customize/readmes/README.md
templates/disk-virt-sysprep/examples/disk-virt-sysprep-taskrun-workspace.yaml
templates/disk-virt-sysprep/examples/disk-virt-sysprep-taskrun.yaml
templates/disk-virt-sysprep/readmes/README.md

chore: change the IDs in securityContext of PipelineRuns/TaskRuns
The IDs defined in securityContext of example PipelineRuns are not accurate. The disk has preset IDs 107 (qemu user). It makes sense to use the same IDs for PipelineRun / TaskRun.
Added mention and solution about issue with permission denied in disk-virt tasks readmes.
```
NONE
```

chore: change the IDs in securityContext of PipelineRuns/TaskRuns

---

release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
templates-pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml

fix: missing acceptEula param in win10 PipelineRun
```
fix: missing acceptEula param in win10 PipelineRun
```

fix: missing acceptEula param in win10 PipelineRun

---

release/tasks/modify-windows-iso-file/modify-windows-iso-file.yaml
templates/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml

chore: log hash of the iso everytime
modify-windows-iso-file task should log the iso hash everytime not only during error
```
chore: log hash of the iso everytime
```

chore: log hash of the iso everytime

---

modules/copy-template/pkg/templates/template-provider.go
modules/copy-template/pkg/utils/parse/clioptions.go
modules/shared/pkg/ownerreference/ownerreference.go
release/tasks/copy-template/README.md
release/tasks/copy-template/copy-template.yaml
templates/copy-template/manifests/copy-template.yaml
test/constants/copy-template.go
test/copy_template_test.go
test/testconfigs/copy-template-config.go

chore: add owner references to copy-template task
If this parameter is set to true, the task add ownerreference
to newly created template and binds it to the task run pod.
This will help during cleanup of objects.
```
chore: add owner references to copy-template task
```

chore: add owner references to copy-template task

---

modules/create-vm/pkg/utils/parse/clioptions.go
modules/create-vm/pkg/vmcreator/vm-creator.go
release/tasks/create-vm-from-manifest/README.md
release/tasks/create-vm-from-manifest/create-vm-from-manifest.yaml
release/tasks/create-vm-from-template/README.md
release/tasks/create-vm-from-template/create-vm-from-template.yaml
templates/create-vm-from-manifest/manifests/create-vm.yaml
test/create_vm_from_manifest_test.go
test/create_vm_from_template_test.go
test/testconfigs/vm-test-config.go

chore: add ownerReference param to create-vm tasks
This commit adds new param setOwnerReference to create-vm tasks. If set to true, the VM object will have OwnerReference by TaskRun pod.
```
chore: add ownerReference param to create-vm tasks
```

chore: add ownerReference param to create-vm tasks

---

modules/modify-data-object/pkg/dataobject/provider.go
modules/modify-data-object/pkg/utils/parse/clioptions.go
release/tasks/modify-data-object/README.md
release/tasks/modify-data-object/modify-data-object.yaml
templates/modify-data-object/manifests/modify-data-object.yaml
test/modify_data_object_test.go
test/testconfigs/modify-data-object-test-config.go

chore: add ownerReference param to modify-data-object task
This commit adds new param setOwnerReference to modify-data-object tasks. If set to true, the data object will have OwnerReference by TaskRun pod.
```
chore: add ownerReference param to modify-data-object task
```

chore: add ownerReference param to modify-data-object task

---

release/pipelines/windows-customize/README.md
release/pipelines/windows-customize/windows-customize.yaml
release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/windows-efi-installer.yaml
templates-pipelines/windows-customize/README.md
templates-pipelines/windows-customize/manifests/windows-customize.yaml
templates-pipelines/windows-efi-installer/README.md
templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml

chore: insert OwnerReferences param to pipelines
sometimes the pipeline can fail and cleanup tasks are not triggered. By inserting the ownerReferences to created objects, when the pipelineRun fails, they can still be deleted by deleting the pipelineRun
```
chore: insert OwnerReferences param to pipelines
```

chore: insert OwnerReferences param to pipelines

---

renovate.json

this commit adds renovate settings for creating PRs with only security updates for branch release-v0.17
```
Enable renovate with security updates only
```

[release-v0.17] enable Renovate

---

renovate.json

chore: update renovate config
Add sign off of commit and no release note label
```
NONE
```

[release-v0.17] chore: update renovate config

---

release/pipelines/windows-efi-installer/README.md
release/pipelines/windows-efi-installer/windows-efi-installer.yaml
templates-pipelines/windows-efi-installer/README.md
templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml

chore: add useBiosMode parameter to efi-pipeline
Windows preferences in older KubeVirt versions might still use Bios mode. In that case, set the `useBiosMode` parameter to `true`. This will skip the `modify-windows-iso-file` task. In case the the Windows preference uses Bios and the `useBiosMode` parameter is not set to true, the Windows VM will not work.
```
chore: add useBiosMode parameter to efi-pipeline
```

chore: add useBiosMode parameter to efi-pipeline

---

renovate.json

this commit adds renovate settings for creating PRs with only security updates for branch release-v0.13
```
NONE
```

[release-v0.13] chore: enable renovate

---

renovate.json

enable renovate for these branches: release-v0.15, release-v0.13, release-v0.12
```
NONE
```

chore: enable renovate for older release branches

---

go.mod

fix: lower the go version in go.mod
The ds automation requires lower version of go specified in go.mod file
```
NONE
```

fix: lower the go version in go.mod

---

renovate.json

chore: update config of renovate
this commit adds ignorePaths to ignore modules/tests folder, because it updates a lot of packages which are unnecessary in release branches.
Removed constraints with hardcoded go version for main. 
Moved extends to the top of the file.
```
NONE
```

chore: update config of renovate

---

automation/e2e-deploy-resources.sh

fix: pin tekton version to v0.67.0
e2e are failing because newest operator is not working on OCP 4.14. This commit is pinning the tekton to v0.67.0
```
NONE
```

[release-v0.15] fix: pin tekton version to v0.67.0

---

renovate.json

chore: enable dependency dashboard for Renovate
```
NONE
```

chore: enable dependency dashboard for Renovate

---

automation/e2e-deploy-resources.sh
modules/tests/test/create_vm_from_template_test.go
modules/tests/test/test_suite_test.go

[release-v0.13] fix: change fedora template from tiny to medium
fedora tiny was removed from common-templates. The e2e tests need to be adjusted to use fedora medium template.
[release-v0.13] fix: pin cdi version to v1.55.2
CDI changed in newer versions statuses on import of DVs and due to that,
some e2e tests are failing
```
NONE
```

[release-v0.13] fix: e2e tests

---

examples/pipelines/server-deployer/server-deployer-pipeline.yaml
examples/pipelines/unit-tester/unit-tester-pipeline.yaml
examples/pipelines/virt-sysprep-updater/virt-sysprep-updater-pipeline.yaml
modules/sharedtest/testobjects/alpine-vm.go
modules/sharedtest/testobjects/fedora-cloud-vm.go
modules/sharedtest/testobjects/template/cirros-tiny.go
modules/sharedtest/testobjects/template/fedora-tiny.go
modules/sharedtest/testobjects/template/rhel-tiny.go
modules/sharedtest/testobjects/vm.go
release/tasks/create-vm-from-manifest/README.md
templates/create-vm-from-manifest/examples/vm.yaml
test/create_vm_from_manifest_test.go
test/create_vm_from_template_test.go
test/execute_and_cleanup_vm_test.go

There is a plan to deprecate spec.running
and instead spec.runStrategy should be
used. Requested by KubeVirt maintainers
to ensure that repositories already have
spec.runStrategy implemented.
Fixes #515.
```release-note
Use spec.runStrategy instead of spec.running
```

refactor: use spec.runStrategy instead of spec.running

---

automation/e2e-deploy-resources.sh

fix: hardcode instance-types version to 1.1.0
newest instance types (v1.2.0) can't work with kubevirt 1.3.1. We have to wait until the new kubevirt version is out
```
NONE
```

fix: hardcode instance-types version to 1.1.0

---

release/tasks/disk-uploader/README.md
release/tasks/disk-uploader/disk-uploader.yaml
templates/disk-uploader/manifests/disk-uploader.yaml

Add a new parameter secret-name which allows user to define another secret than only "kubevirt-disk-uploader-credentials-tekton".
```release-note
Add a new secret-name parameter
```

fix(CNV-50417): enable usage of a custom secret

---

modules/modify-data-object/pkg/dataobject/provider.go
modules/modify-data-object/pkg/utils/parse/clioptions.go
modules/modify-data-object/pkg/utils/parse/clioptions_test.go
release/tasks/modify-data-object/README.md
release/tasks/modify-data-object/modify-data-object.yaml
templates/modify-data-object/manifests/modify-data-object.yaml

feat: add timeout parameter to modify-data-object tasks
When importing data object from slow server and wait-for-success param is set to true, one hour of timeout might not be enough. This commit introduces new parameter timeout where user can increase / decrease time necessary to import data object. Defaul value is 1 hour.
```
feat: add timeout parameter to modify-data-object tasks
```

feat: add timeout parameter to modify-data-object task

---

automation/e2e-deploy-resources.sh

feat: enable VMPersistentState feature gate in kubevirt
windows VMs (run in e2e pipeline tests) requires this fg.
```
NONE
```

feat: enable VMPersistentState feature gate in kubevirt

---

automation/e2e-deploy-resources.sh

feat: remove deployment of instance types in e2e tests
instance types are now deployed by kubevirt
```
NONE
```

feat: remove deployment of instance types in e2e tests

---

examples/pipelines/disk-uploader/disk-uploader-role.yaml

The disk-uploader should be able to
access Data Volume or Presistent
Volume Claim to get the InstanceType
and Preference labels from them,
and set in the newly created
containerDisk.
```release-note
None
```

fix(CNV-40411): add new disk-uploader roles

---

cmd/disk-uploader/main.go
modules/disk-uploader/pkg/secrets/secrets.go
modules/disk-uploader/pkg/secrets/secrets_test.go
modules/disk-uploader/pkg/vmexport/vmexport.go
modules/disk-uploader/pkg/vmexport/vmexport_test.go

When running disk-uploader it creates
VMExport object and VMExport secret
to store a token that required by the
Export API endpoints.
Currently the name of VMExport object
and VMExport secret is not random
generated and will fail to be created
again if the disk-uploader (as a Tekton
Task) will run twice. As a result, it
throws a panic error that causes the
failure of the execution.
Fixes #542.
```release-note
Generate random name of objects
```

fix(CNV-52011): create objects with random names

---

release/tasks/disk-uploader/README.md
release/tasks/disk-uploader/disk-uploader.yaml
release/tasks/disk-uploader/examples/taskruns/disk-uploader-taskrun-resolver.yaml
templates/disk-uploader/examples/disk-uploader-taskrun.yaml
templates/disk-uploader/manifests/disk-uploader.yaml

Tekton parameter PUSH_TIMEOUT is not required
and can use default value if not set, which is
timeout of 2 hours (120 minutes).
```release-note
PUSH_TIMEOUT parameter is optional.
```

fix(CNV-53189): make PUSH_TIMEOUT an optional param

---

release/tasks/disk-uploader/disk-uploader.yaml
templates/disk-uploader/manifests/disk-uploader.yaml

Currently the downloaded disk image from
the source will be stored inside container's
temporary file system, that consumes RAM,
and instead it should be stored in the node's
storage by using emptyDir.
```release-note
Use emptyDir to store downloaded disk in disk-uploader.
```

fix(CNV-53190): use emptyDir to store downloaded disk

---

configs/disk-uploader.yaml
examples/pipelines/disk-uploader/disk-uploader-pipelinerun.yaml
release/tasks/disk-uploader/README.md
release/tasks/disk-uploader/disk-uploader.yaml
release/tasks/disk-uploader/examples/taskruns/disk-uploader-secret.yaml
release/tasks/disk-uploader/examples/taskruns/disk-uploader-taskrun-resolver.yaml
templates/disk-uploader/examples/disk-uploader-taskrun.yaml
templates/disk-uploader/generate-task.yaml
templates/disk-uploader/manifests/disk-uploader.yaml
templates/disk-uploader/readmes/README.md

Add more details to explain an usage of
EXPORT_SOURCE_KIND. Also, Add an example of the
Secret object, that will be referenced by
SECRET_NAME.
```release-note
None
```

docs(CNV-53188): improve disk-uploader usage guidance

---

cmd/disk-uploader/main.go
modules/disk-uploader/pkg/vmexport/vmexport.go

Currently disk-uploader will always show
ready status, and there is no indication
of pending status that could mean of an
used export source (e.g. an used PVC that
is not available to be exported).
```release-note
Show status of used export sources.
```

fix(CNV-54663): show status of used export sources

---

cmd/disk-uploader/main.go
modules/shared/pkg/results/results.go

feat: do not exit with error when tekton result folder does not exists in disk-uploader
Disk uploader binary can be triggered via Tekton Tasks or via OCP UI in
disk uploader feature. When UI triggers the binary, binary is looking for
Tekton result folder, which does not exist and ends with error.
If the Tekton result folder is not found, the binary will just exit with
0.
```
feat: do not exit with error when tekton result folder does not exists in disk-uploader
```

feat: do not exit with error when tekton result folder does not exists in disk-uploader

---

renovate.json

feat: simplify renovate configuration
use regex for branches, instead of hardcoding.
removed go version constraints as they were not working the way we need. Removed unnecessary rules for packages on release branches. Disabled grouping of the dependencies into single PR - this should help to bump dependencies more easier, because PR with more dependencies, have more chances, that it will introduce incompatible dependencies
```release-note
NONE
```

feat: simplify renovate configuration

---

automation/e2e-deploy-resources.sh
modules/tests/test/create_vm_from_template_test.go
modules/tests/test/test_suite_test.go

fix:insert tag in common templates URL in deploy resource script
change ssp api version
update version of fedora template used in e2e tests
```release-note
NONE
```

[release-v0.16] fix:insert tag in common templates URL in deploy resource script

---

modules/disk-uploader/pkg/vmexport/vmexport.go

feat: increate poll interval from 15 seconds to 60 seconds
the 15 seconds poll intervall is too short and if user tries to export bigger disk, it puts too much messages in the log. The value is increased to 60 seconds
```release-note
NONE
```

feat: increate poll interval from 15 seconds to 60 seconds

---

modules/disk-uploader/pkg/vmexport/vmexport_test.go
modules/wait-for-vmi-status/pkg/requirements/lookup_test.go
modules/wait-for-vmi-status/pkg/requirements/requirements_suite_test.go
modules/wait-for-vmi-status/pkg/requirements/requirements_test.go
scripts/test-with-reports.sh

fix: test-with-reports makefile target
the script was checking if module contains go.mod file and if not it skips the module. The go.mod files were removed and only one is kept in the root of the project. This PR removes the check for go.mod file and fixes failing unit tests.
```release-note
NONE
```

fix: test-with-reports makefile target

---

modules/disk-uploader/pkg/vmexport/vmexport.go
modules/disk-uploader/pkg/vmexport/vmexport_test.go

fix: when vmExport is in skipped phase, exit the disk uploader task
vm export cannot recover from skipped phase and thus it doesn't make sense to wait.
**Which issue(s) this PR fixes**:
Fixes: https://issues.redhat.com/browse/CNV-56960
```release-note
fix: when vmExport is in skipped phase, exit the disk uploader task
```

fix: when vmExport is in skipped phase, exit the disk uploader task

---

release/pipelines/windows-efi-installer/windows-efi-installer.yaml
templates-pipelines/windows-efi-installer/manifests/windows-efi-installer.yaml

feat: bump virtio win image version in installer pipeline
follow up - modify https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt-tekton-tasks/tekton-tasks-periodics.yaml#L32
```release-note
feat: bump virtio win image version in installer pipeline
```

feat: bump virtio win image version in installer pipeline

---

build/Containerfile
build/Containerfile.DiskVirt
release/tasks/cleanup-vm/cleanup-vm.yaml
release/tasks/create-vm-from-manifest/create-vm-from-manifest.yaml
release/tasks/disk-uploader/disk-uploader.yaml
release/tasks/disk-virt-customize/disk-virt-customize.yaml
release/tasks/disk-virt-sysprep/disk-virt-sysprep.yaml
release/tasks/execute-in-vm/execute-in-vm.yaml
release/tasks/generate-ssh-keys/generate-ssh-keys.yaml
release/tasks/modify-data-object/modify-data-object.yaml
release/tasks/wait-for-vmi-status/wait-for-vmi-status.yaml
scripts/build-release-images.sh
scripts/push-release-images.sh
templates/create-vm-from-manifest/manifests/create-vm.yaml
templates/disk-uploader/manifests/disk-uploader.yaml
templates/disk-virt-customize/manifests/disk-virt-customize.yaml
templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
templates/execute-in-vm/manifests/execute-in-vm.yaml
templates/generate-ssh-keys/manifests/generate-ssh-keys.yaml
templates/modify-data-object/manifests/modify-data-object.yaml
templates/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml

As of now Tekton kubevirt tasks supported only on x86/amd64. so this PR will add support for s390x, arm64 cpu platforms.
Fixes #
```release-note
NONE
```

add multiarch support for kubevirt tasks

---

automation/e2e-pipelines/test-files/windows11-dv.yaml
release/pipelines/windows-customize/configmaps/windows-customize-configmaps.yaml
templates-pipelines/windows-customize/configmaps/windows-customize-configmaps.yaml

fix: update example windows customize configmap
Latest Windows 11 24h2 contains bug, which is causing the VM to boot into BSOD. This is happening because, when VM is syspreped and bitlocker is enabled, bitlocker modifies bootloader parameters, which then forces VM to boot into BSOD. This PR is updating the Win11 unattend xml and adding commands which fixes the parameters for bootloader.
```
NONE
```

fix: update example windows customize configmap

---

test/create_vm_from_manifest_test.go

fix: failing e2e test
In azure clusters, the e2e test "VM is created from manifest properly" is failing, because created VM has populated spec.template.spec.domain.firmware struct, which is populated with random ID during creation
Fixes #
```release-note
NONE
```

fix: failing e2e test

---

automation/e2e-deploy-resources.sh

fix: hardcode ssp operator to version v0.19.1
Newest SSP operator contains operands, which do
not work on older OCP versions
```release-note
NONE
```

[release-v0.17] fix: hardcode ssp operator to version v0.19.1

---

automation/e2e-pipelines/example-pipelines-test.sh

fix: e2e example pipeline tests
The pipeline tests stoped working because of missing information in storageProfile. This commit adds patch command, which adds the missing information in ssd storageProfile.
```release-note
NONE
```

fix: e2e example pipeline tests
