- automation/e2e-tests.sh
- automation/generatetasks/build/bin/user_setup
- modules/create-vm/pkg/utils/parse/clioptions_test.go
- modules/shared/pkg/env/env_test.go
- remove unit tests which depend on a presence/no presence of being in a cluster
> fix tests and CI

- automation/e2e-deploy-resources.sh
- modules/create-vm/makefile
- scripts/cluster-sync.sh
- scripts/cluster-test.sh
- scripts/makefile-snippets/makefile-deploy-dev.mk
- scripts/makefile-snippets/makefile-deploy.mk
- tasks/create-vm/makefile
- use always oc client
- make CREATE_VM_IMAGE configurable
> make better scripts and automation

- automation/build-test.sh
- automation/e2e-deploy-resources.sh
- automation/e2e-tests.sh
- makefile
- modules/create-vm/makefile
- modules/shared/makefile
- scripts/cluster-test.sh
- scripts/makefile-snippets/makefile-golang-test.mk
- scripts/test-with-reports.sh
> add test-with-reports script + CI

- makefile
- modules/tests/test/test_suite_test.go
- scripts/cluster-test.sh
- scripts/makefile-snippets/makefile-generate-task.mk
- scripts/makefile-snippets/makefile-golang-test.mk
- scripts/test-with-reports.sh
- scripts/test-yaml-consistency.sh
- tasks/create-vm/makefile
> fix tests exit codes

- automation/e2e-tests.sh
- modules/tests/test/test_suite_test.go
- modules/tests/test/utils/utils.go
> add DEV_MODE to e2e-tests + CI debug info

- automation/e2e-deploy-resources.sh
> force openshift namespace for templates

- automation/e2e-deploy-resources.sh
- automation/e2e-tests.sh
- modules/tests/test/framework/clients.go
- modules/tests/test/test_suite_test.go
> fix CI scripts and test suite

- configs/create-vm.yaml
- scripts/cluster-sync.sh
- tasks/create-vm/manifests/create-vm-from-template.yaml
> move create-vm image under kubevirt

- automation/e2e-tests.sh
- githooks/pre-commit
- makefile
- modules/create-vm/makefile
- scripts/clean.sh
- scripts/cluster-sync.sh
- scripts/common.sh
- scripts/deploy-tasks.sh
- scripts/lint-fix.sh
- scripts/lint.sh
- scripts/makefile-snippets/makefile-golang-test.mk
- scripts/onboard-new-task-with-ci-stub.sh
- scripts/test-with-reports.sh
- scripts/test-yaml-consistency.sh
- scripts/test.sh
- move logic from makefile to scripts folder and refactor a bit (exit codes, etc. )
- add onboard-new-task-with-ci-stub help script
> move logic and add onboard-new-task-with-ci-stub script

- tasks/create-datavolume/README.md
- tasks/create-vm/README.md
> fix README links

- configs/cleanup-vm.yaml
- configs/create-vm.yaml
- configs/execute-in-vm.yaml
- modules/execute-in-vm/build/execute-in-vm/Dockerfile
- scripts/onboard-new-task-with-ci-stub.sh
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/create-vm/manifests/create-vm-from-template.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
> bump create-vm task and update dockerfiles

- README.md
- configs/cleanup-vm.yaml
- configs/create-vm-from-manifest.yaml
- configs/create-vm-from-template.yaml
- configs/execute-in-vm.yaml
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/create-vm-from-manifest/README.md
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/README.md
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- templates/create-vm-from-template/generate-task.yaml
- templates/create-vm-from-template/readmes/README.md
> release create-vm v0.0.3 and execute-in-vm v0.0.2 images & fix READMEs

- modules/create-vm/makefile
- modules/execute-in-vm/build/execute-in-vm/Dockerfile
- modules/execute-in-vm/makefile
> fix Dockerfile + scripts

- README.md
- tasks/cleanup-vm/README.md
- tasks/create-datavolume-from-manifest/README.md
- tasks/create-vm-from-manifest/README.md
- tasks/create-vm-from-template/README.md
- tasks/execute-in-vm/README.md
- tasks/execute-in-vm/examples/taskruns/execute-in-vm-with-ssh-taskrun.yaml
- templates/create-datavolume-from-manifest/readmes/README.md
- templates/create-vm-from-manifest/readmes/README.md
- templates/create-vm-from-template/readmes/README.md
- templates/execute-in-vm/examples/execute-in-vm-taskrun.yaml
- templates/execute-in-vm/readmes/README.md
> add better READMEs

- README.md
I try to explain why running your tests inside a VM may be required.
> README: improve English style, add motivation

- examples/pipelines/unit-tester/README.md
names changed in https://github.com/kubevirt/kubevirt-tekton-tasks/pull/53
> fix unit tester README

- configs/cleanup-vm.yaml
- configs/create-vm-from-manifest.yaml
- configs/create-vm-from-template.yaml
- configs/execute-in-vm.yaml
- configs/generate-ssh-keys.yaml
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
> release new create-vm, execute-in-vm and generate-ssh-keys images

- .gitattributes
- README.md
- configs/create-vm-from-template.yaml
- manifests/kubernetes/kubevirt-tekton-tasks.yaml
- manifests/openshift/kubevirt-tekton-tasks.yaml
- scripts/generate-yaml-tasks.sh
- scripts/test-yaml-consistency.sh
- tasks/cleanup-vm/README.md
- tasks/create-datavolume-from-manifest/README.md
- tasks/create-vm-from-manifest/README.md
- tasks/create-vm-from-template/README.md
- tasks/execute-in-vm/README.md
- tasks/generate-ssh-keys/README.md
- templates/create-datavolume-from-manifest/readmes/README.md
- templates/create-vm-from-manifest/readmes/README.md
- templates/create-vm-from-template/readmes/README.md
- templates/execute-in-vm/readmes/README.md
- templates/generate-ssh-keys/readmes/README.md
- add generated manifests of combined tasks
> add Deployment section to main README + generate combined manifests

- tasks/cleanup-vm/README.md
- tasks/create-datavolume-from-manifest/README.md
- tasks/create-vm-from-manifest/README.md
- tasks/create-vm-from-template/README.md
- tasks/execute-in-vm/README.md
- tasks/generate-ssh-keys/README.md
- templates/create-datavolume-from-manifest/readmes/README.md
- templates/create-vm-from-manifest/readmes/README.md
- templates/create-vm-from-template/readmes/README.md
- templates/disk-virt-customize/readmes/README.md
- templates/execute-in-vm/readmes/README.md
- templates/generate-ssh-keys/readmes/README.md
> link RBAC doc from task READMEs

- configs/cleanup-vm.yaml
- configs/create-vm-from-manifest.yaml
- configs/create-vm-from-template.yaml
- configs/disk-virt-customize.yaml
- configs/execute-in-vm.yaml
- configs/generate-ssh-keys.yaml
- manifests/kubernetes/kubevirt-tekton-tasks.yaml
- manifests/openshift/kubevirt-tekton-tasks.yaml
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
> release new image versions

- README.md
> link to the latest release in main README

- modules/generate-ssh-keys/pkg/secret/secret_creator.go
> add better logging to generate-ssh-keys

- tasks/disk-virt-sysprep/README.md
- templates/disk-virt-sysprep/readmes/README.md
> fix disk-virt-sysprep README headline

- configs/create-vm-from-manifest.yaml
- configs/create-vm-from-template.yaml
- manifests/kubernetes/kubevirt-tekton-tasks.yaml
- manifests/openshift/kubevirt-tekton-tasks.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
> bump create-vm image version

- modules/tests/test/framework/testoptions/test-options.go
- modules/tests/test/testconfigs/dv-test-config.go
- modules/tests/test/testconfigs/execute-in-vm-test-config.go
- modules/tests/test/testconfigs/generate-ssh-keys-test-config.go
- modules/tests/test/testconfigs/vm-test-config.go
> refactor namespace resolution in tests

- configs/cleanup-vm.yaml
- configs/execute-in-vm.yaml
- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/openshift/kubevirt-tekton-tasks-openshift.yaml
- modules/execute-in-vm/pkg/execute/executor.go
- modules/tests/test/execute_and_cleanup_vm_test.go
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- take Succeeded and Failed statuses into account
- bump execute-in-vm image version
> execute-in-vm/cleanup-vm: fix wait for stop option

- README.md
- automation/e2e-deploy-resources.sh
- configs/create-vm-from-template.yaml
- docs/getting-started.md
- examples/pipelines/windows-installer/README.md
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- modules/tests/test/constants/constants.go
- modules/tests/test/create_vm_common_test.go
- modules/tests/test/create_vm_from_template_test.go
- modules/tests/test/framework/testoptions/test-options.go
- modules/tests/test/test_suite_test.go
- scripts/cluster-clean.sh
- scripts/cluster-sync.sh
- scripts/cluster-test.sh
- scripts/common.sh
- scripts/generate-yaml-tasks.sh
- scripts/test-yaml-consistency.sh
- tasks/create-vm-from-template/README.md
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- templates/create-vm-from-manifest/manifests/create-vm.yaml
- templates/create-vm-from-template/readmes/README.md
fixes https://github.com/kubevirt/kubevirt-tekton-tasks/issues/86
cc @mazzystr
> branding: rename Openshift to OKD

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> add github templates for new PR and new issue

- scripts/onboard-new-task-with-ci-stub.sh
update onboard-new-task-with-ci-stub.sh script
This PR updates onboard script with ONLY_OKD variable and updates
builder image in newly created dockerfile. ONLY_OKD variable adds is_okd: true
line in task config file.
```
NONE
```
> update onboard-new-task-with-ci-stub.sh script

- README.md
add modify-vm-template link in main readme
```
NONE
```
> add modify-vm-template link in main readme

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.5.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.5.0

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.6.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.6.0

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.7.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.7.0

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.8.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.8.0

- automation/generatetasks/build/Dockerfile
add packages golang, git, which to a builder dockerfile
```
NONE
```
> add packages golang, git, which to a builder dockerfile

- automation/e2e-deploy-resources.sh
create tekton-pipelines namespace during tests
```
NONE
```
> create tekton-pipelines namespace during tests

- configs/create-datavolume-from-manifest.yaml
- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- tasks/create-datavolume-from-manifest/manifests/create-datavolume-from-manifest.yaml
bump origin-cli version image to 4.11
```
bump origin-cli version image to 4.11
```
> bump origin-cli version image to 4.11

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.9.1 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.9.1

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.9.2 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.9.2

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.9.3 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.9.3

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-data-object/manifests/create-data-object.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.10.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.10.0

- examples/pipelines/windows10-customize/README.md
- examples/pipelines/windows10-installer/README.md
Add notice to cleanup-vm that is is always exectued and update the order
of tasks.
```release-note
None
```
> Update docs of example pipelines

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- tasks/disk-virt-customize/examples/taskruns/disk-virt-customize-taskrun-workspace.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/examples/taskruns/disk-virt-sysprep-taskrun-workspace.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- templates/disk-virt-customize/examples/disk-virt-customize-taskrun-workspace.yaml
- templates/disk-virt-customize/examples/disk-virt-customize-taskrun.yaml
- templates/disk-virt-customize/generate-task.yaml
- templates/disk-virt-customize/manifests/disk-virt-customize.yaml
- templates/disk-virt-sysprep/examples/disk-virt-sysprep-taskrun-workspace.yaml
- templates/disk-virt-sysprep/generate-task.yaml
- templates/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
This allows to pass customization data or secrets to be consumed during
the run of virt-customize or virt-sysprep.
This will be especially useful when https://github.com/tektoncd/pipeline/pull/5085 is merged.
```release-note
Add workspace to disk-virt-customize and disk-virt-sysprep
```
> Add workspace to disk-virt-[customize|sysprep]

- modules/tests/test/constants/timeout.go
- modules/tests/test/framework/framework.go
- modules/tests/test/pipelines_test.go
- modules/tests/test/runner/pipelinerunner.go
- modules/tests/test/tekton/pipelinerun.go
- modules/tests/test/tekton/utils.go
- modules/tests/test/testconfigs/pipeline-test-config.go
- modules/tests/test/testconfigs/test-config.go
This commit adds support for pipelineRuns and testing of pipelines into
testing framework.
```
NONE
```
> add support for pipelineRuns in testing framework

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.11.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.11.0

- modules/tests/go.mod
- modules/tests/go.sum
- modules/tests/test/test_suite_test.go
- modules/tests/vendor/kubevirt.io/client-go/reporter/reporter.go
- modules/tests/vendor/kubevirt.io/qe-tools/LICENSE
- modules/tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
- modules/tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
- modules/tests/vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
- modules/tests/vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
- modules/tests/vendor/modules.txt
- scripts/cluster-test.sh
update code which generates test reports
this change allows user to specify where junit report will be generated
and allows to generate polarion report
```
NONE
```
> update code which generates test reports

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.12.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.12.0

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.12.1 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.12.1

- OWNERS
Really add 0xFelix to approvers
```release-note
None
```
> Really add 0xFelix to approvers

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.13.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.13.0

- modules/tests/test/create_vm_common_test.go
fix: flaky vm create test
the test failed a lot of time due to already existing datavolume. This was caused by a string which changed during test run and all test runs had the same string. This PRs moves the test to a
already existing context, where the string is set and do not change during test.
```
NONE
```
> fix: flaky vm create test

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.13.1 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.13.1

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.13.2 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.13.2

- examples/pipelines/windows-bios-installer/README.md
- examples/pipelines/windows-customize/README.md
- examples/pipelines/windows-efi-installer/README.md
feat: add cancell/delete tip for example pipelines
This PR adds into documentation paragraph, which explaination how should users cancel/delete pipelineRun.
```
NONE
```
> feat: add cancell/delete tip for example pipelines

- OWNERS
feat: update OWNERS file
```
NONE
```
> feat: update OWNERS file

- README.md
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- tasks/copy-template/README.md
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-template/README.md
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/modify-vm-template/README.md
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- templates/copy-template/manifests/copy-template.yaml
- templates/copy-template/readmes/README.md
- templates/create-vm-from-manifest/manifests/create-vm.yaml
- templates/create-vm-from-template/readmes/README.md
- templates/modify-vm-template/manifests/modify-vm-template.yaml
- templates/modify-vm-template/readmes/README.md
This PR adds deprecation annotation to the tasks that will be deprecated and removed in future versions.
```
None
```
> Add deprecation annotations

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.13.3 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.13.3

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.14.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.14.0

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.15.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.15.0

- .github/workflows/release.yaml
Reverts kubevirt/kubevirt-tekton-tasks#249
> Revert "feat: Change ssp master to main"

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.16.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.16.0

- .snyk
feat: add snyk file for excluding vendor folders
Vendor folders should not be testet by snyk integration
```
NONE
```
> feat: add snyk file for excluding vendor folders

- modules/tests/go.mod
- modules/tests/go.sum
- modules/tests/vendor/github.com/golang/glog/glog.go
- modules/tests/vendor/github.com/golang/glog/glog_file.go
- modules/tests/vendor/github.com/golang/glog/glog_file_linux.go
- modules/tests/vendor/github.com/golang/glog/glog_file_other.go
- modules/tests/vendor/github.com/golang/glog/glog_file_posix.go
- modules/tests/vendor/github.com/golang/glog/glog_flags.go
- modules/tests/vendor/google.golang.org/grpc/README.md
- modules/tests/vendor/google.golang.org/grpc/attributes/attributes.go
- modules/tests/vendor/google.golang.org/grpc/balancer/balancer.go
- modules/tests/vendor/google.golang.org/grpc/clientconn.go
- modules/tests/vendor/google.golang.org/grpc/dialoptions.go
- modules/tests/vendor/google.golang.org/grpc/encoding/encoding.go
- modules/tests/vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
- modules/tests/vendor/google.golang.org/grpc/internal/backoff/backoff.go
- modules/tests/vendor/google.golang.org/grpc/internal/internal.go
- modules/tests/vendor/google.golang.org/grpc/internal/status/status.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/handler_server.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/http2_client.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/http2_server.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/http_util.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/transport.go
- modules/tests/vendor/google.golang.org/grpc/server.go
- modules/tests/vendor/google.golang.org/grpc/tap/tap.go
- modules/tests/vendor/google.golang.org/grpc/version.go
- modules/tests/vendor/google.golang.org/grpc/vet.sh
- modules/tests/vendor/modules.txt
Bump google.golang.org/grpc to the latest version.
Fixes #
```release-note
None
```
> [release-v0.16] chore: Bump google.golang.org/grpc

- modules/tests/go.mod
- modules/tests/go.sum
- modules/tests/vendor/github.com/golang/glog/glog.go
- modules/tests/vendor/github.com/golang/glog/glog_file.go
- modules/tests/vendor/github.com/golang/glog/glog_file_linux.go
- modules/tests/vendor/github.com/golang/glog/glog_file_other.go
- modules/tests/vendor/github.com/golang/glog/glog_file_posix.go
- modules/tests/vendor/github.com/golang/glog/glog_flags.go
- modules/tests/vendor/google.golang.org/grpc/README.md
- modules/tests/vendor/google.golang.org/grpc/attributes/attributes.go
- modules/tests/vendor/google.golang.org/grpc/balancer/balancer.go
- modules/tests/vendor/google.golang.org/grpc/clientconn.go
- modules/tests/vendor/google.golang.org/grpc/dialoptions.go
- modules/tests/vendor/google.golang.org/grpc/encoding/encoding.go
- modules/tests/vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
- modules/tests/vendor/google.golang.org/grpc/internal/backoff/backoff.go
- modules/tests/vendor/google.golang.org/grpc/internal/internal.go
- modules/tests/vendor/google.golang.org/grpc/internal/status/status.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/handler_server.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/http2_client.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/http2_server.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/http_util.go
- modules/tests/vendor/google.golang.org/grpc/internal/transport/transport.go
- modules/tests/vendor/google.golang.org/grpc/server.go
- modules/tests/vendor/google.golang.org/grpc/tap/tap.go
- modules/tests/vendor/google.golang.org/grpc/version.go
- modules/tests/vendor/google.golang.org/grpc/vet.sh
- modules/tests/vendor/modules.txt
Bump google.golang.org/grpc to the latest version.
Fixes #
```release-note
None
```
> chore: Bump google.golang.org/grpc

- .snyk
feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```
> [release-v0.12]feat: add .snyk file

- .snyk
feat: add .snyk file
This file is used for excluding vendor folders from snyk code scans
```release-note
NONE
```
> [release-v0.13]feat: add .snyk file

- manifests/kubernetes/kubevirt-tekton-tasks-kubernetes.yaml
- manifests/okd/kubevirt-tekton-tasks-okd.yaml
- scripts/makefile-snippets/makefile-release.mk
- tasks/cleanup-vm/manifests/cleanup-vm.yaml
- tasks/copy-template/manifests/copy-template.yaml
- tasks/create-vm-from-manifest/manifests/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/manifests/create-vm-from-template.yaml
- tasks/disk-virt-customize/manifests/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/manifests/disk-virt-sysprep.yaml
- tasks/execute-in-vm/manifests/execute-in-vm.yaml
- tasks/generate-ssh-keys/manifests/generate-ssh-keys.yaml
- tasks/modify-data-object/manifests/modify-data-object.yaml
- tasks/modify-vm-template/manifests/modify-vm-template.yaml
- tasks/modify-windows-iso-file/manifests/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/manifests/wait-for-vmi-status.yaml
Update tekton tasks manifests to version v0.17.0 
```release-note
NONE
```
> Update tekton tasks manifests to version v0.17.0

- modules/modify-data-object/pkg/dataobject/provider.go
fix: race condition when allowReplace is true in modify-data-object task
modify-data-object is not waiting until dv/ds/pvc is deleted when allowReplace is set to true and it
tries to recreate the object. Sometimes the object still exists and task run ends with error that object still exists. This commit adds waiting functions which will make sure object no longer exists
```
fix: race condition when allowReplace is true in modify-data-object task
```
> fix: race condition when allowReplace is true in modify-data-object task

- scripts/deploy-tasks.sh
fix: replacing of images in deploy-task.sh script
The deploy-task.sh script did not correctly replace images in task manifests which contain more than one image. This commit changes the way, how the image links are replaced in manifests. It replaces all occurences of tekton-tasks and tekton-tasks-disk-virt images with custom one if custom image (TEKTON_TASKS_IMAGE) is defined .
```
NONE
```
> fix: replacing of images in deploy-task.sh script

- release/pipelines/windows-bios-installer/README.md
- release/pipelines/windows-bios-installer/configmaps/windows-bios-installer-configmaps.yaml
- release/pipelines/windows-bios-installer/getisourl.py
- release/pipelines/windows-bios-installer/pipelineruns/pipelineruns.yaml
- release/pipelines/windows-bios-installer/windows-bios-installer.yaml
- release/pipelines/windows-customize/README.md
- release/pipelines/windows-customize/configmaps/windows-customize-configmaps.yaml
- release/pipelines/windows-customize/pipelineruns/pipelineruns.yaml
- release/pipelines/windows-customize/windows-customize.yaml
- release/pipelines/windows-efi-installer/README.md
- release/pipelines/windows-efi-installer/configmaps/windows-efi-installer-configmaps.yaml
- release/pipelines/windows-efi-installer/getisourl.py
- release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
- release/pipelines/windows-efi-installer/windows-efi-installer.yaml
- tasks/cleanup-vm/cleanup-vm.yaml
- tasks/copy-template/copy-template.yaml
- tasks/create-vm-from-manifest/create-vm-from-manifest.yaml
- tasks/create-vm-from-template/create-vm-from-template.yaml
- tasks/disk-virt-customize/disk-virt-customize.yaml
- tasks/disk-virt-sysprep/disk-virt-sysprep.yaml
- tasks/execute-in-vm/execute-in-vm.yaml
- tasks/generate-ssh-keys/generate-ssh-keys.yaml
- tasks/modify-data-object/modify-data-object.yaml
- tasks/modify-vm-template/modify-vm-template.yaml
- tasks/modify-windows-iso-file/modify-windows-iso-file.yaml
- tasks/wait-for-vmi-status/wait-for-vmi-status.yaml
This PR regenerates manifests from #332
```
NONE
```
> chore: Generate manifests from #332

- README.md
chore: add artifact hub badge to README
```
NONE
```
> chore: add artifact hub badge to README

- release/pipelines/windows-bios-installer/README.md
- release/pipelines/windows-customize/README.md
- release/pipelines/windows-efi-installer/README.md
- scripts/ansible/branding.yaml
- templates-pipelines/windows-bios-installer/README.md
- templates-pipelines/windows-customize/README.md
- templates-pipelines/windows-efi-installer/README.md
chore: add variables for requirement in pipeline readmes
this change will help during modification in downstream
```
NONE
```
> chore: add variables for requirement in pipeline readmes

- README.md
The tasks sub-directory was moved under the release directory from v0.18. Consequently, the links in the main README.md are broken.
**Which issue(s) this PR fixes** :
Fixes # (Issue doesn't exist: fixing directly)
```release-note
NONE
```
> Fix: Broken Link Fixes in main Readme.md (tasks/ -> release/tasks/)

- scripts/deploy-tasks.sh
fix: deploy-task.sh script
deploy-task.sh script incorrectly replaces URL to images when used in local envs.
```
NONE
```
> fix: deploy-task.sh script

- release/pipelines/windows-efi-installer/README.md
- release/pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
- templates-pipelines/windows-efi-installer/pipelineruns/pipelineruns.yaml
chore: add win10 efi pipelinerun example
```
chore: add win10 efi pipelinerun example
```
> chore: add win10 pipelinerun example

- release/pipelines/windows-efi-installer/README.md
- release/pipelines/windows-efi-installer/configmaps/windows-efi-installer-configmaps.yaml
- scripts/deploy-pipelines.sh
- templates-pipelines/windows-efi-installer/README.md
- templates-pipelines/windows-efi-installer/configmaps/windows-efi-installer-configmaps.yaml
fix: put false value in accept eula xml tag
instead of commenting the eula, put a false value in accept eula tag.
update README
```
fix: put false value in accept eula xml tag
```
> fix: put false value in accept eula xml tag

- automation/e2e-pipelines/example-pipelines-test.sh
chore: improve checking if the pipelinerun succeeded in e2e tests
previously the script waited for the state of pipelinerun, even the pipelinerun has already succeeded. This commit updates to behaviour to end immediatelly if the pipelinerun is finished
```
NONE
```
> chore: improve checking if the pipelinerun succeeded in e2e tests

- scripts/test.sh
fix: unit tests
this commit is fixing triggering of unit tests
```
NONE
```
> fix: unit tests

- OWNERS
chore: add Geetika as reviewer
```
NONE
```
> chore: add Geetika as reviewer

- automation/e2e-deploy-resources.sh
- modules/tests/test/create_vm_from_template_test.go
- modules/tests/test/test_suite_test.go
This is an cherry-pick of https://github.com/kubevirt/kubevirt-tekton-tasks/pull/498 and fix for the newest common templates
```
NONE
```
> [release-v0.15] Cherry pick 498 to release v0.15

- cmd/disk-uploader/main.go
Change the order of the logging and remove unnecessary logs.
```release-note
None
```
> fix(CNV-54663): improve disk-uploader logs

- automation/e2e-deploy-resources.sh
fix: hardcode ssp operator to version v0.18.3
Newest SSP operator contains operands, which do
not work on older OCP versions
```release-note
NONE
```
> [release-v0.15] fix: hardcode ssp operator to version v0.18.3
